# Generated by Django 4.1.3 on 2022-11-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_purcahse'),
    ]

    operations = [
        migrations.AddField(
            model_name='purcahse',
            name='additional_info',
            field=models.TextField(default='a'),
        ),
    ]
